# Generated by Django 5.0.2 on 2024-06-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='card',
            name='instructor',
        ),
    ]
